### ISSUE TITLE
net.arnx.wmf2svg.gdi.wmf.WmfParseException: invalid file format

### ISSUE THREAD

**Issue by angel1magic** [hidekatsu-izuno/wmf2svg#16]
I get the following error when converting WMF to [SVG：](url)
net.arnx.wmf2svg.gdi.wmf.WmfParseException: invalid file format.
	at net.arnx.wmf2svg.gdi.wmf.WmfParser.parse(WmfParser.java:75)
	at WmfToPng.wmfToSvg(WmfToPng.java:177)
	at WmfToPng.convert(WmfToPng.java:93)
	at WmfToPng.main(WmfToPng.java:39)

[test3.zip](https://github.com/hidekatsu-izuno/wmf2svg/files/9206121/test3.zip)

help！！！！

**Comment by hidekatsu-izuno** [comment]
Did not reproduce. you passed a zip file. WMF2SVG does not support a zipped wmf file.
