### ISSUE TITLE
emf file support

### ISSUE THREAD

**Issue by riyuuli** [hidekatsu-izuno/wmf2svg#3]
could type of emf file be supported ?

**Comment by riyuuli** [comment]
freehep works for emf, close this issue.

**Comment by yura** [comment]
Can't convert EMF file:

```
net.arnx.wmf2svg.gdi.wmf.WmfParseException: invalid file format.
	at net.arnx.wmf2svg.gdi.wmf.WmfParser.parse(WmfParser.java:75)
	at net.arnx.wmf2svg.Main.main(Main.java:138)
```
